album/urls.py
from django.urls import path
from . import views

app_name = 'album'

urlpatterns = [
    path('upload/', views.upload, name='upload'),
    path('showall/', views.showall, name='showall'),
    path('betails/', views.betails, name='betails'),
    path('<int:id>/edit', views.edit, name='edit'),
    path('<int:id>/delete', views.delete, name='delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import base, RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('album/', include('album.urls')),
    path('admin/', admin.site.urls),
    path('accounts/login/', base.RedirectView.as_view(pattern_name="polls:login")),
    path('accounts/profile/', base.RedirectView.as_view(pattern_name="polls:index")),
    path('', RedirectView.as_view(url='/polls/login/')),
] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name="polls/login.html"), name='login'),
    path('index.html', views.index),
    path('kyoto.html', views.kyoto),
    path('kyotocty.html', views.kyotocty),
]

polls/models.py
import datetime
from django.utils import timezone
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/forms.py
from django import forms
from .models import Question, Choice
from django.contrib.auth.models import User


class VoteForm(forms.Form):
    new_option = forms.CharField(max_length=200, required=False)

    def __init__(self, *args, **kwargs):
        self.question = kwargs.pop('question')
        super(VoteForm, self).__init__(*args, **kwargs)
        CHOICES = [(ch.id, ch.choice_text) for ch in self.question.choice_set.all()]
        CHOICES.append((-1, 'other option (please specify in the box below)'))
        self.fields['your_choice'] = forms.ChoiceField(choices = CHOICES, widget=forms.RadioSelect())

    def clean_your_choice(self):
        your_choice = self.cleaned_data.get('your_choice')
        return int(your_choice)

    def clean(self):
        super(VoteForm, self).clean()
        choice_id = self.cleaned_data.get('your_choice')
        new_option = self.cleaned_data.get('new_option')
        if choice_id < 0:
            if not new_option:
                raise forms.ValidationError(
                    'Please specify a new option (or choose an existing one)!'
                    )
        else:
            if new_option:
                raise forms.ValidationError(
                    'Do not specify a new option with also choosing an existing one!'
                    )

    def save(self):
        choice_id = self.cleaned_data.get('your_choice')
        if choice_id < 0:
            new_option = Choice(
                question=self.question,
                choice_text=self.cleaned_data.get('new_option'),
                votes=0
                )
            new_option.save()
        else:
            selected_choice = Choice.objects.get(pk=choice_id)
            selected_choice.votes += 1
            selected_choice.save()
            
class SignUpForm(forms.Form):
    username = forms.CharField(label='ユーザー名', widget=forms.TextInput)
    enter_password = forms.CharField(label='パスワード', widget=forms.PasswordInput)
    retype_password = forms.CharField(label='再度パスワード', widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('The username has been already taken.')
        return username

    def clean_enter_password(self):
        password = self.cleaned_data.get('enter_password')
        if len(password) < 5:
            raise forms.ValidationError('Password must contain 5 or more characters.')
        return password

    def clean(self):
        super(SignUpForm, self).clean()
        password = self.cleaned_data.get('enter_password')
        retyped = self.cleaned_data.get('retype_password')
        if password and retyped and (password != retyped):
            self.add_error('retype_password', 'This does not match with the above.')

    def save(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('enter_password')
        new_user = User.objects.create_user(username = username)
        new_user.set_password(password)
        new_user.save()

polls/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Choice
from .forms import *


def index(request):
    latest_question_list = Question.objects.all().order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)
    
def kyoto(request):
    latest_question_list = Question.objects.all().order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/kyoto.html')

def kyotocty(request):
    latest_question_list = Question.objects.all().order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/kyotocty.html')

@login_required
def detail(request, question_id):
    user = request.user
    question = get_object_or_404(Question, pk=question_id)

    if request.method == 'POST':
        form = VoteForm(request.POST, question=question)
        if form.is_valid():
            form.save()
            return redirect('polls:results', question_id=question.id)
    else:
        form = VoteForm(question=question)

    context = {'user':user, 'question':question, 'form':form}
    return render(request, "polls/detail.html", context)

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('polls:index')
    else:
        form = SignUpForm()

    context = {'form':form}
    return render(request, 'polls/signup.html', context)

polls/templates/polls/home.html
<!DOCTYPE html> {% load static %} {% bootstrap_css %}
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
        <a class="navbar-brand" href="/polls/home.html">観光アプリ</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="navbar-toggler-icon" ></span></a>
                    <div class="dropdown-menu-right dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="/polls/home.html">ホーム</a>
                        <a class="dropdown-item" href="/album/upload">投稿する</a>
                        <a class="dropdown-item" href="/album/betails">投稿履歴</a>
                        <a class="dropdown-item" href="/polls/login/">ログアウト</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    <div class="contents">
        <div class="container">
            <ul class="gnav">
                <li>
                    <a href="">エリア一覧</a>
                    <ul>
                        <li>
                            <a href="">近畿</a>
                            <ul>
                                <li>
                                    <a href="">	京都府</a>
                                    <ul>
                                        <li><a href="">京都市</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <div class="touristname">
                    <div class="image">
                        <img src="/media/officialimages/mksk.png" width="10" height="30" class="example1">
                    </div>
                    <div class="spotname">
                        <a href="/album/showall">
                            <h3 class="basicTitle">清水寺</h3>
                        </a>
                    </div>
                    <div class="sightseeingimage">
                        <a href="/album/showall"><img src="/media/officialimages/01_kiyomizu1.jpg" width="800" height="400"></a>
                    </div>
                </div>
        </div>
    </div>
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

</html>

polls/templates/polls/index.html
<!DOCTYPE html> {% load static %} {% bootstrap_css %}

<head>
    <title>観光アプリ</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <title>観光アプリ</title>
</head>

<body>
    <header>
        <div class="navbar navbar-dark bg-primary shadow-sm">
            <a href="/polls/index.html" class="navbar-brand">
                    <strong>観光アプリ</strong>
                </a>
            <div class="menulist">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="dropdown-menu-right dropdown-menu" aria-labelledby="navbarDropdownMenuLink" id="navbarSupportedContent">
                    <a class="dropdown-item" href="/polls/index.html">ホーム</a>
                    <a class="dropdown-item" href="/album/upload">投稿する</a>
                    <a class="dropdown-item" href="/album/betails">投稿履歴</a>
                    <a class="dropdown-item" href="/polls/login/">ログアウト</a>
                </div>
            </div>
        </div>
    </header>
    <main>
        <div class="contents">
            <div class="container">
                <ul class="gnav">
                    <li>
                        <a href="/polls/index.html">エリア一覧</a>
                        <ul>
                            <li>
                                <a href="/polls/index.html">近畿</a>
                                <ul>
                                    <li>
                                        <a href="/polls/kyoto.html">京都府</a>
                                        <ul>
                                            <li><a href="/polls/kyotocty.html">京都市</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <div class="touristname">
                        <div class="image">
                            <img src="/media/officialimages/aaa.png" width="10" height="30" class="example1">
                        </div>
                        <div class="spotname">
                            <a href="/album/showall">
                                <h3 class="basicTitle">清水寺</h3>
                            </a>
                        </div>
                        <div class="sightseeingimage">
                            <a href="/album/showall"><img src="/media/officialimages/ksji.jpg" width="850" height="430"></a>
                        </div>
                    </div>
                    <div class="touristname">
                        <div class="image">
                            <img src="/media/officialimages/aaa.png" width="10" height="30" class="example1">
                        </div>
                        <div class="spotname">
                            <a href="#">
                                <h3 class="basicTitle">大阪城</h3>
                            </a>
                        </div>
                        <div class="sightseeingimage">
                            <a href="#"><img src="/media/officialimages/skee.png" width="850" height="430"></a>
                        </div>
                    </div>
                    <div class="touristname">
                        <div class="image">
                            <img src="/media/officialimages/aaa.png" width="10" height="30" class="example1">
                        </div>
                        <div class="spotname">
                            <a href="#">
                                <h3 class="basicTitle">ゆめさき苺ハウス</h3>
                            </a>
                        </div>
                        <div class="sightseeingimage">
                            <a href="#"><img src="/media/officialimages/yumesaki0.jpg" width="850" height="430"></a>
                        </div>
                    </div>
                    <div class="touristname">
                        <div class="image">
                            <img src="/media/officialimages/aaa.png" width="10" height="30" class="example1">
                        </div>
                        <div class="spotname">
                            <a href="#">
                                <h3 class="basicTitle">彦根城</h3>
                            </a>
                        </div>
                        <div class="sightseeingimage">
                            <a href="#"><img src="/media/officialimages/skeee.png" width="850" height="430"></a>
                        </div>
                    </div>
                    <div class="touristname">
                        <div class="image">
                            <img src="/media/officialimages/aaa.png" width="10" height="30" class="example1">
                        </div>
                        <div class="spotname">
                            <a href="#">
                                <h3 class="basicTitle">アドベンチャーワールド</h3>
                            </a>
                        </div>
                        <div class="sightseeingimage">
                            <a href="#"><img src="/media/officialimages/ksje.png" width="850" height="430"></a>
                        </div>
                    </div>
                </ul>
            </div>
        </div>
    </main>
</body>

</html>

polls/templates/polls/kyoto.html
<!DOCTYPE html> {% load static %} {% bootstrap_css %}

<head>
    <title>観光アプリ</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <title>観光アプリ</title>
</head>

<body>
    <header>
        <div class="navbar navbar-dark bg-primary shadow-sm">
            <a href="/polls/index.html" class="navbar-brand">
                    <strong>観光アプリ</strong>
                </a>
            <div class="menulist">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="dropdown-menu-right dropdown-menu" aria-labelledby="navbarDropdownMenuLink" id="navbarSupportedContent">
                    <a class="dropdown-item" href="/polls/index.html">ホーム</a>
                    <a class="dropdown-item" href="/album/upload">投稿する</a>
                    <a class="dropdown-item" href="/album/betails">投稿履歴</a>
                    <a class="dropdown-item" href="/polls/login/">ログアウト</a>
                </div>
            </div>
        </div>
    </header>
    <main>
        <div class="contents">
            <div class="container">
                <ul class="gnav">
                    <li>
                        <a href="">エリア一覧</a>
                        <ul>
                            <li>
                                <a href="/polls/index.html">近畿</a>
                                <ul>
                                    <li>
                                        <a href="/polls/kyoto.html">京都府</a>
                                        <ul>
                                            <li><a href="/polls/kyotocty.html">京都市</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <div class="touristname">
                        <div class="image">
                            <img src="/media/officialimages/aaa.png" width="10" height="30" class="example1">
                        </div>
                        <div class="spotname">
                            <a href="/album/showall">
                                <h3 class="basicTitle">清水寺</h3>
                            </a>
                        </div>
                        <div class="sightseeingimage">
                            <a href="/album/showall"><img src="/media/officialimages/ksji.jpg" width="850" height="430"></a>
                        </div>
                    </div>
                    <div class="touristname">
                        <div class="image">
                            <img src="/media/officialimages/aaa.png" width="10" height="30" class="example1">
                        </div>
                        <div class="spotname">
                            <a href="#">
                                <h3 class="basicTitle">天岩戸神社</h3>
                            </a>
                        </div>
                        <div class="sightseeingimage">
                            <a href="#"><img src="/media/officialimages/sssd.jpg" width="850" height="430"></a>
                        </div>
                    </div>
                    <div class="touristname">
                        <div class="image">
                            <img src="/media/officialimages/aaa.png" width="10" height="30" class="example1">
                        </div>
                        <div class="spotname">
                            <a href="#">
                                <h3 class="basicTitle">舞鶴赤れんがパーク</h3>
                            </a>
                        </div>
                        <div class="sightseeingimage">
                            <a href="#"><img src="/media/officialimages/sded.jpg" width="850" height="430"></a>
                        </div>
                    </div>
                    <div class="touristname">
                        <div class="image">
                            <img src="/media/officialimages/aaa.png" width="10" height="30" class="example1">
                        </div>
                        <div class="spotname">
                            <a href="#">
                                <h3 class="basicTitle">光明寺</h3>
                            </a>
                        </div>
                        <div class="sightseeingimage">
                            <a href="#"><img src="/media/officialimages/dada.jpg" width="850" height="430"></a>
                        </div>
                    </div>
                    <div class="touristname">
                        <div class="image">
                            <img src="/media/officialimages/aaa.png" width="10" height="30" class="example1">
                        </div>
                        <div class="spotname">
                            <a href="#">
                                <h3 class="basicTitle">平等院</h3>
                            </a>
                        </div>
                        <div class="sightseeingimage">
                            <a href="#"><img src="/media/officialimages/slop.jpg" width="850" height="430"></a>
                        </div>
                    </div>
                </ul>
            </div>
        </div>
    </main>
</body>

</html>

polls/templates/polls/login.html
<!DOCTYPE html> {% load static %} {% bootstrap_css %}
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div class="box">
        <img src="/media/officialimages/asdw.png" width="930" height="840" class="example1">
        <form action="{% url 'polls:login' %}" method="post">
            <div class="jumbotron">
                {% csrf_token %} {{ form.as_p }}
                <p><input class="decorated" type="submit" value="ログイン"></p>
                <a class="btn btn-primary" href="{% url 'polls:signup' %}" role="button">アカウント登録</a>
            </div>
        </form>
    </div>
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

</html>

polls/templates/polls/signup.html
<!DOCTYPE html> {% load static %} {% bootstrap_css %}
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/signup.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<div class="box">
    <div class="text-image">
        <img src="/media/officialimages/asdw.png" width="930" height="840" class="example1">
        <form action="{% url 'polls:signup' %}" method="post">
            <div class="jumbotron">
                {% csrf_token %} {{ form.as_p }}
                <p><input class="decorated" type="submit" value="アカウント登録"></p>
                <a class="btn btn-primary" href="{% url 'polls:login' %}" role="button">ログイン</a>
            </div>
        </form>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

</html>